#ifndef __EvtMyPanel5__
#define __EvtMyPanel5__

/**
@file
Subclass of MyPanel5, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include

/** Implementing MyPanel5 */
class EvtMyPanel5 : public MyPanel5
{
	public:
		/** Constructor */
		EvtMyPanel5( wxWindow* parent );
	//// end generated class members




};

#endif // __EvtMyPanel5__
