.PHONY: clean All

All:
	@echo "----------Building project:[ supervision_software - Debug ]----------"
	@cd "supervision_software" && "$(MAKE)" -f  "supervision_software.mk"
clean:
	@echo "----------Cleaning project:[ supervision_software - Debug ]----------"
	@cd "supervision_software" && "$(MAKE)" -f  "supervision_software.mk" clean
